CREATE SCHEMA soil_and_pimp_live AUTHORIZATION DBA;


CREATE TABLE soil_and_pimp_live.page (
  page_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  page_name varchar(45) NOT NULL,
  css LONGVARCHAR NOT NULL,
  default_background varchar(45),
  click_count int DEFAULT 0,
  PRIMARY KEY (page_id)
);

CREATE TABLE soil_and_pimp_live.media (
  media_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  page_id int NOT NULL,
  media_type varchar(45) NOT NULL,
  file_name varchar(255) NOT NULL,
  file_type varchar(45) NOT NULL,
  file_data BLOB NOT NULL,
  file_size int NOT NULL,
  PRIMARY KEY (media_id),
  FOREIGN KEY (page_id) REFERENCES moe_sounds.page(page_id)
);
