CREATE SCHEMA soil_and_pimp_live AUTHORIZATION DBA;

CREATE TABLE soil_and_pimp_live.events (
  event_key varchar(50),
  name LONGVARCHAR NOT NULL,
  social_networking_title LONGVARCHAR,
  memo LONGVARCHAR,
  event_url LONGVARCHAR,
  jvc_url LONGVARCHAR,
  open_date TIMESTAMP,
  schedule_change BOOLEAN,
  broadcast BOOLEAN,
  PRIMARY KEY (event_key)
);

CREATE TABLE soil_and_pimp_live.schedules (
  schedule_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1  INCREMENT BY 1),
  event_key varchar(50) NOT NULL,
  "date" date,
  enter_time varchar(45),
  start_time varchar(45),
  prefecture LONGVARCHAR,
  place LONGVARCHAR,
  "call" LONGVARCHAR,
  memo LONGVARCHAR,
  link LONGVARCHAR,
  PRIMARY KEY (schedule_id),
  FOREIGN KEY (event_key) REFERENCES soil_and_pimp_live.events(event_key)
);

CREATE TABLE soil_and_pimp_live.email_subscriptions (
  email_address varchar(100),
  verification_token varchar(45) NULL,
  verified BOOLEAN NOT NULL,
  created_date DATE NOT NULL,
  PRIMARY KEY (email_address)
);
